security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
                path:     /
            logout:
                path:   app_logout
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

    access_control:
         - { path: ^/adminPanel, roles: ROLE_ADMIN }
