name:
    label: 'Название стоматологии'
    value: Стомасвiт
title:
    label: Заглавие
    value: 'ЦЕ ОПЕРАТИВНА І ЯКІСНА СТОМАТОЛОГІЯ'
metro:
    label: Метро
    value: 'м. Нивки'
description:
    label: Описание
    value: 'Сучасне обладнання, дизайн, сервіс відповідає останнім вимогам стоматології, включає широкий спектр можливостей для лікаря при максимальному комфорті для пацієнта. Висококваліфіковані і досвідчені фахівці допоможуть Вам підібрати оптимальну схему лікування, врахують всі Ваші побажання, а також в наших клініках Ви можете отримати рекомендації по догляду за порожниною рота. Персонал, який пройшов спеціальне навчання, простежить за тим, що б Ви відчували себе комфортно і затишно в кімнаті очікування і кріслі лікаря-стоматолога.'
address:
    label: Адрес
    value: 'Данила Щербаківького ,52'
phone:
    label: Телефон
    value: '044 227-19-20'
why_we:
    label: 'Почему к нам'
    value: 'це оперативна і якісна стоматологія. Сучасне обладнання, дизайн, сервіс відповідає останнім вимогам стоматології, включає широкий спектр можливостей для лікаря при максимальному комфорті для пацієнта.'
