name:
    label: 'Название стоматологии'
    value: Стомасвiт
title:
    label: Заглавие
    value: 'ЦЕ ОПЕРАТИВНА І ЯКІСНА СТОМАТОЛОГІЯ'
metro:
    label: Метро
    value: 'м. Нивки'
description:
    label: Описание
    value: 'Сучасне обладнання, дизайн, сервіс відповідає останнім вимогам стоматології, включає широкий спектр можливостей для лікаря при максимальному комфорті для пацієнта. Висококваліфіковані і досвідчені фахівці допоможуть Вам підібрати оптимальну схему лікування, врахують всі Ваші побажання, а також в наших клініках Ви можете отримати рекомендації по догляду за порожниною рота. Персонал, який пройшов спеціальне навчання, простежить за тим, що б Ви відчували себе комфортно і затишно в кімнаті очікування і кріслі лікаря-стоматолога.'
address:
    label: Адрес
    value: 'Данила Щербаківського, 52'
phone:
    label: 'Телефон в хедере'
    value: '044 227-19-20'
phone_textarea:
    label: 'Телефоны на странице контактов'
    value: '<p><a href="tel:044 227-19-20">044 227-19-20</a></p><p><a href="tel:044 227-19-20">044 227-19-20</a></p><p><a href="tel:055-5353-5353">055-5353-5353</a></p><p><a href="tel:425053-5353-53-535">425053-5353-53-535</a></p>'
    textarea: true
why_we:
    label: 'Почему стоит обратиться к нам'
    value: 'це оперативна і якісна стоматологія. Сучасне обладнання, дизайн, сервіс відповідає останнім вимогам стоматології, включає широкий спектр можливостей для лікаря при максимальному комфорті для пацієнта.'
seo_title_main:
    label: 'Сео тайтл на главной'
    value: Стомасвит
seo_description_main:
    label: 'Сео описание на главной'
    value: 'Стомасвит описание'
seo_title_service:
    label: 'Сео тайтл в услугах'
    value: 'Услуги стомасвит'
seo_description_service:
    label: 'Сео описание в услугах'
    value: 'Услуги стомасвит описание'
seo_title_promotion:
    label: 'Сео тайтл в акциях'
    value: 'Акции стомасвит'
seo_description_promotion:
    label: 'Сео описание в акциях'
    value: 'Акции стомасвит описание'
seo_title_doctors:
    label: 'Сео тайтл на врачах'
    value: 'Врачи стомасвит'
seo_description_doctors:
    label: 'Сео описание на врачах'
    value: 'Врачи стомасвит описание'
seo_title_reviews:
    label: 'Сео тайтл на пациентах'
    value: 'Пациентам стомасвит'
seo_description_reviews:
    label: 'Сео описание на пациентах'
    value: 'Пациентам стомасвит описание'
