#admin
admin_index:
    path: /adminPanel
    controller: App\Controller\Admin\MainController::index
main_page_slider_index:
    path: /adminPanel/main_page_slider
    controller: App\Controller\Admin\MainPageSliderController::index
main_page_slider_create:
    path: /adminPanel/main_page_slider/create
    controller: App\Controller\Admin\MainPageSliderController::create
main_page_slider_update:
    path: /adminPanel/main_page_slider/update/{id}
    controller: App\Controller\Admin\MainPageSliderController::update
main_page_slider_update_queue:
    path: /adminPanel/main_page_slider/update_queue/
    controller: App\Controller\Admin\MainPageSliderController::updateQueue
    methods: POST
main_page_slider_delete:
    path: /adminPanel/main_page_slider/delete/{id}
    controller: App\Controller\Admin\MainPageSliderController::delete
service_index:
    path: /adminPanel/service
    controller: App\Controller\Admin\ServiceController::index
service_create:
    path: /adminPanel/service/create
    controller: App\Controller\Admin\ServiceController::create
service_update:
    path: /adminPanel/service/update/{id}
    controller: App\Controller\Admin\ServiceController::update
service_queue:
    path: /adminPanel/service/update_queue/
    controller: App\Controller\Admin\ServiceController::updateQueue
    methods: POST
service_delete:
    path: /adminPanel/service/delete/{id}
    controller: App\Controller\Admin\ServiceController::delete
app_logout:
    path: /logout
    methods: GET
