index:
    path: /
    controller: App\Controller\pages\MainController::index
admin_index:
    path: /adminPanel
    controller: App\Controller\Admin\MainController::index
app_logout:
    path: /logout
    methods: GET
