#pages
index:
    path: /
    controller: App\Controller\Pages\MainController::index
service_main:
    path: /services
    controller: App\Controller\Pages\ServiceController::index
service_single:
    path: /service-{slug}
    controller: App\Controller\Pages\ServiceController::singleService
doctor_main:
    path: /doctors
    controller: App\Controller\Pages\DoctorController::index
doctor_single:
    path: /doctor-{slug}
    controller: App\Controller\Pages\DoctorController::singleDoctor
#admin_panel
admin_index:
    path: /adminPanel
    controller: App\Controller\Admin\MainController::index
#slider
main_page_slider_index:
    path: /adminPanel/main_page_slider
    controller: App\Controller\Admin\MainPageSliderController::index
main_page_slider_create:
    path: /adminPanel/main_page_slider/create
    controller: App\Controller\Admin\MainPageSliderController::create
main_page_slider_update:
    path: /adminPanel/main_page_slider/update/{id}
    controller: App\Controller\Admin\MainPageSliderController::update
main_page_slider_update_queue:
    path: /adminPanel/main_page_slider/update_queue/
    controller: App\Controller\Admin\MainPageSliderController::updateQueue
    methods: POST
main_page_slider_delete:
    path: /adminPanel/main_page_slider/delete/{id}
    controller: App\Controller\Admin\MainPageSliderController::delete
#service
service_index:
    path: /adminPanel/service
    controller: App\Controller\Admin\ServiceController::index
service_create:
    path: /adminPanel/service/create
    controller: App\Controller\Admin\ServiceController::create
service_update:
    path: /adminPanel/service/update/{id}
    controller: App\Controller\Admin\ServiceController::update
service_queue:
    path: /adminPanel/service/update_queue/
    controller: App\Controller\Admin\ServiceController::updateQueue
    methods: POST
service_delete:
    path: /adminPanel/service/delete/{id}
    controller: App\Controller\Admin\ServiceController::delete
#mini_service
mini_service_index:
    path: /adminPanel/mini_service
    controller: App\Controller\Admin\MiniServiceController::index
mini_service_create:
    path: /adminPanel/mini_service/create
    controller: App\Controller\Admin\MiniServiceController::create
mini_service_api_create:
    path: /adminPanel/api/mini_service/create
    controller: App\Controller\Admin\MiniServiceController::apiCreate
mini_service_update:
    path: /adminPanel/mini_service/update/{id}
    controller: App\Controller\Admin\MiniServiceController::update
mini_service_delete:
    path: /adminPanel/mini_service/delete/{id}
    controller: App\Controller\Admin\MiniServiceController::delete
#doctor
doctor_index:
    path: /adminPanel/doctor
    controller: App\Controller\Admin\DoctorController::index
doctor_create:
    path: /adminPanel/doctor/create
    controller: App\Controller\Admin\DoctorController::create
doctor_update:
    path: /adminPanel/doctor/update/{id}
    controller: App\Controller\Admin\DoctorController::update
doctor_queue:
    path: /adminPanel/doctor/update_queue/
    controller: App\Controller\Admin\DoctorController::updateQueue
    methods: POST
doctor_delete:
    path: /adminPanel/doctor/delete/{id}
    controller: App\Controller\Admin\DoctorController::delete
#certificate
sertificate_index:
    path: /adminPanel/sertificate
    controller: App\Controller\Admin\SertificateController::index
sertificate_create:
    path: /adminPanel/sertificate/create
    controller: App\Controller\Admin\SertificateController::create
sertificate_update:
    path: /adminPanel/sertificate/update/{id}
    controller: App\Controller\Admin\SertificateController::update
sertificate_queue:
    path: /adminPanel/sertificate/update_queue/
    controller: App\Controller\Admin\SertificateController::updateQueue
    methods: POST
sertificate_delete:
    path: /adminPanel/sertificate/delete/{id}
    controller: App\Controller\Admin\SertificateController::delete
#review
review_index:
    path: /adminPanel/review
    controller: App\Controller\Admin\ReviewController::index
review_create:
    path: /adminPanel/review/create
    controller: App\Controller\Admin\ReviewController::create
review_update:
    path: /adminPanel/review/update/{id}
    controller: App\Controller\Admin\ReviewController::update
review_queue:
    path: /adminPanel/review/update_queue/
    controller: App\Controller\Admin\ReviewController::updateQueue
    methods: POST
review_delete:
    path: /adminPanel/review/delete/{id}
    controller: App\Controller\Admin\ReviewController::delete
#promotion
promotion_index:
    path: /adminPanel/promotion
    controller: App\Controller\Admin\PromotionController::index
promotion_create:
    path: /adminPanel/promotion/create
    controller: App\Controller\Admin\PromotionController::create
promotion_update:
    path: /adminPanel/promotion/update/{id}
    controller: App\Controller\Admin\PromotionController::update
promotion_update_active:
    path: /adminPanel/promotion/update_active/
    controller: App\Controller\Admin\PromotionController::updateActive
    methods: POST
promotion_update_public:
    path: /adminPanel/promotion/update_public/
    controller: App\Controller\Admin\PromotionController::updatePublic
    methods: POST
promotion_queue:
    path: /adminPanel/promotion/update_queue/
    controller: App\Controller\Admin\PromotionController::updateQueue
    methods: POST
promotion_delete:
    path: /adminPanel/promotion/delete/{id}
    controller: App\Controller\Admin\PromotionController::delete
#common_settings
common_settings_index:
    path: /adminPanel/settings
    controller: App\Controller\Admin\SettingsController::index
common_settings_update:
    path: /adminPanel/settings/update/
    controller: App\Controller\Admin\SettingsController::update
#logout
app_logout:
    path: /logout
    methods: GET
